java_test(
    name = "snowblossomlib.test",
    test_class = "snowblossomlib.test.AllTests",
    srcs = glob(["**/*.java", "*.java"]),
    deps = [
        "//snowblossomlib:snowblossomlib",
        "//snowblossomprotolib:snowblossomprotolib",
    ]
)