#!/bin/bash
# node entrypoint

set -eu

cd /data

cat <<EOF > /tmp/node.conf
env_override_prefix=snow_node_
log_config_file=${SNOWBLOSSOM_LOG_CONF:-log.conf}
network=${SNOWBLOSSOM_NETWORK:-mainnet}
db_type=${SNOWBLOSSOM_NODE_DB_TYPE:-rocksdb}
db_path=${SNOWBLOSSOM_NODE_DB_PATH:-node_db/mainnet}
addr_index=${SNOWBLOSSOM_NODE_ADDRESS_INDEX:-true}
tx_index=${SNOWBLOSSOM_NODE_TRANSACTION_INDEX:-true}
service_port=${SNOWBLOSSOM_NODE_PORT:-2338}
tls_service_port=${SNOWBLOSSOM_TLS_SERVICE_PORT:-2348}
tls_key_path=${SNOWBLOSSOM_NODE_TLS_PATH:-node_db/tls_mainnet}
EOF

cp /tmp/node.conf ./
[[ ! -f log.conf ]] && cp /snowblossom/log.conf ./
[[ ! -d logs ]] && mkdir logs

exec /snowblossom/scripts/snowblossom snowblossom.node.SnowBlossomNode node.conf
