#!/bin/bash
# node entrypoint

set -eu

cd /data

cat <<EOF > /tmp/node.conf
log_config_file=${SNOWBLOSSOM_LOG_CONF:-log.conf}
network=${SNOWBLOSSOM_NETWORK:-mainnet}
db_type=${SNOWBLOSSOM_NODE_DB_TYPE:-rocksdb}
db_path=${SNOWBLOSSOM_NODE_DB_PATH:-node_db/mainnet}
addr_index=${SNOWBLOSSOM_NODE_ADDRESS_INDEX:-false}
tx_index=${SNOWBLOSSOM_NODE_TRANSACTION_INDEX:-false}
service_port=${SNOWBLOSSOM_NODE_PORT:-2338}
EOF

cp /tmp/node.conf ./
[[ ! -f log.conf ]] && cp /snowblossom/log.conf ./
[[ ! -d logs ]] && mkdir logs

bash /snowblossom/scripts/snowblossom snowblossom.node.SnowBlossomNode node.conf
