#!/bin/bash
# node entrypoint

set -eu

cd /data

cat <<EOF > /tmp/pool.conf
env_override_prefix=snow_pool_
log_config_file=${SNOWBLOSSOM_LOG_CONF:-log.conf}
EOF

cp /tmp/pool.conf ./
[[ ! -f log.conf ]] && cp /snowblossom/log.conf ./
[[ ! -d logs ]] && mkdir logs

bash /snowblossom/scripts/snowblossom snowblossom.miner.plow.MrPlow pool.conf
