package(default_visibility = ["//visibility:public"])

java_test(
    name = "systemtests.test.SpoonTestBasic",
    test_class = "systemtests.test.SpoonTestBasic",
    srcs = ["test/SpoonTest.java", "test/SpoonTestBasic.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "medium",
)

java_test(
    name = "systemtests.test.SpoonTestFbo",
    test_class = "systemtests.test.SpoonTestFbo",
    srcs = ["test/SpoonTest.java", "test/SpoonTestFbo.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "medium",
)

java_test(
    name = "systemtests.test.SpoonTestPool",
    test_class = "systemtests.test.SpoonTestPool",
    srcs = ["test/SpoonTest.java", "test/SpoonTestPool.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "medium",
)

java_test(
    name = "systemtests.test.SpoonTestReconsile",
    test_class = "systemtests.test.SpoonTestReconsile",
    srcs = ["test/SpoonTest.java", "test/SpoonTestReconsile.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "medium",
)

java_test(
    name = "systemtests.test.ShardTestBasic",
    test_class = "systemtests.test.ShardTestBasic",
    srcs = ["test/SpoonTest.java", "test/ShardTestBasic.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "medium",
)

java_test(
    name = "systemtests.test.ShardTestFullClaw",
    test_class = "systemtests.test.ShardTestFullClaw",
    srcs = ["test/SpoonTest.java", "test/ShardTestFullClaw.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "medium",
)

java_test(
    name = "systemtests.test.ShardTestPeering",
    test_class = "systemtests.test.ShardTestPeering",
    srcs = ["test/SpoonTest.java", "test/ShardTestPeering.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "medium",
)

java_test(
    name = "systemtests.test.ShardTestJambo",
    test_class = "systemtests.test.ShardTestJambo",
    srcs = ["test/SpoonTest.java", "test/ShardTestJambo.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "medium",
)

java_test(
    name = "systemtests.test.ShardTestPlow",
    test_class = "systemtests.test.ShardTestPlow",
    srcs = ["test/SpoonTest.java", "test/ShardTestPlow.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "medium",
)


java_test(
    name = "systemtests.test.ShardTestFullJambo",
    test_class = "systemtests.test.ShardTestFullJambo",
    srcs = ["test/SpoonTest.java", "test/ShardTestFullJambo.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "large",
)

java_test(
    name = "systemtests.test.ShardTestDuelPool",
    test_class = "systemtests.test.ShardTestDuelPool",
    srcs = ["test/SpoonTest.java", "test/ShardTestDuelPool.java"],
    deps = [
        "//lib:lib",
        "//lib:rocksdb",
        "//protolib:protogrpc",
        "//miner:miner",
        "//node",
        "//client:client",
        "//shackleton:shackleton",
        "@duckutil//:duckutil_lib",
        "@build_stack_rules_proto//java:grpc_netty",
    ],
    size = "large",
)



